In [1]:
import torch

# Tensor

In [2]:
# construct empty tensor filled with unintialized number
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  8.5899e+09,  1.0992e-37],
        [-2.8657e-42,  1.2523e-29,  1.4013e-45],
        [ 1.2555e-29,  1.4013e-45,  1.2555e-29],
        [ 1.4013e-45,  1.2564e-29,  1.4013e-45],
        [ 1.2570e-29,  1.4013e-45,  1.2556e-29]])


In [3]:
#construct a randomly initialized matrix(0~1)
x = torch.rand(5,3)
print(x)

tensor([[0.1127, 0.9848, 0.1151],
        [0.4409, 0.2487, 0.2596],
        [0.2596, 0.3680, 0.2212],
        [0.9597, 0.2806, 0.5214],
        [0.8607, 0.9980, 0.7374]])


In [4]:
#construct a matrix filled with zeros
x = torch.zeros(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
#construct a tensor directly from a data
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
#construct a tensor based on a existing tensor. you can reuse properties(eg. dtype) 
x = x.new_ones(5, 3, dtype = torch.int)
print(x)

x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0.9248, 0.4732, 0.0949],
        [0.8143, 0.7549, 0.1488],
        [0.0046, 0.6145, 0.1120],
        [0.4367, 0.0302, 0.3311],
        [0.9656, 0.5791, 0.4976]])


In [12]:
# construct a tensor mean is 0, variation is 1
x = torch.randn(5, 3)
print(x)

tensor([[ 0.1789,  2.1058, -0.7783],
        [-1.9073,  1.1378, -1.0137],
        [-1.2758,  1.7787,  1.3598],
        [-0.7554,  1.2743,  0.0725],
        [-0.4151,  1.8740, -0.5408]])


In [13]:
#tensor size
print(x.size())

torch.Size([5, 3])


# Tensor Operation

### 1. Add

In [25]:
x = torch.rand(5,3)
y = torch.ones(5,3)
print(x)
print(y)

tensor([[0.0595, 0.6315, 0.9393],
        [0.6289, 0.9304, 0.6160],
        [0.3653, 0.0916, 0.0233],
        [0.6163, 0.4585, 0.3104],
        [0.6292, 0.5259, 0.9132]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [26]:
z = x + y
print(z)

tensor([[1.0595, 1.6315, 1.9393],
        [1.6289, 1.9304, 1.6160],
        [1.3653, 1.0916, 1.0233],
        [1.6163, 1.4585, 1.3104],
        [1.6292, 1.5259, 1.9132]])


In [27]:
z = torch.add(x, y)
print(z)

tensor([[1.0595, 1.6315, 1.9393],
        [1.6289, 1.9304, 1.6160],
        [1.3653, 1.0916, 1.0233],
        [1.6163, 1.4585, 1.3104],
        [1.6292, 1.5259, 1.9132]])


In [28]:
z = torch.empty(5,3)
torch.add(x, y, out = z)
print(z)

tensor([[1.0595, 1.6315, 1.9393],
        [1.6289, 1.9304, 1.6160],
        [1.3653, 1.0916, 1.0233],
        [1.6163, 1.4585, 1.3104],
        [1.6292, 1.5259, 1.9132]])


In [29]:
# adds x to y

y.add_(x)
print('x :', x)
print('y :', y)

x : tensor([[0.0595, 0.6315, 0.9393],
        [0.6289, 0.9304, 0.6160],
        [0.3653, 0.0916, 0.0233],
        [0.6163, 0.4585, 0.3104],
        [0.6292, 0.5259, 0.9132]])
y : tensor([[1.0595, 1.6315, 1.9393],
        [1.6289, 1.9304, 1.6160],
        [1.3653, 1.0916, 1.0233],
        [1.6163, 1.4585, 1.3104],
        [1.6292, 1.5259, 1.9132]])


In [30]:
# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x

### 2. Multiplication

In [31]:
x = torch.rand(5,3)
y = torch.ones(5,3)
print(x)
print(y)

tensor([[0.8295, 0.6913, 0.1650],
        [0.2890, 0.5837, 0.8128],
        [0.9257, 0.0179, 0.3830],
        [0.7213, 0.4103, 0.1171],
        [0.8746, 0.0193, 0.7043]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [32]:
#multiplication by element
z = torch.mul(x, y)
print(z)

tensor([[0.8295, 0.6913, 0.1650],
        [0.2890, 0.5837, 0.8128],
        [0.9257, 0.0179, 0.3830],
        [0.7213, 0.4103, 0.1171],
        [0.8746, 0.0193, 0.7043]])


In [37]:
#dot product

z = torch.tensor([1,2])

torch.dot(z,z)

tensor(5)

In [38]:
#matrix multiplication
z = torch.mm(x,y)
print(z)

tensor([[1.6858, 1.6858, 1.6858, 1.6858, 1.6858],
        [1.6855, 1.6855, 1.6855, 1.6855, 1.6855],
        [1.3265, 1.3265, 1.3265, 1.3265, 1.3265],
        [1.2487, 1.2487, 1.2487, 1.2487, 1.2487],
        [1.5981, 1.5981, 1.5981, 1.5981, 1.5981]])


# Slicing
same with standard numpy slicing

In [30]:
x = torch.arange(1,21, step=1)
print(x)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])


In [33]:
x = x.reshape(4,5) 
print(x)

#you can use torch.view(4,5) for resizing/reshaping
#torch.reshape just copy of original tensor but torch.view make change original tensor

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


In [34]:
x[:,:]

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [35]:
x[1:,:]

tensor([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [36]:
x[2:,3:]

tensor([[14, 15],
        [19, 20]])

# NumPy Bridge

In [42]:
import numpy as np

In [59]:
# numpy to torch
a = np.array([[1,2,3],[4,5,6]])
print('a :', a)

b = torch.from_numpy(a)
print('b :', b)

a : [[1 2 3]
 [4 5 6]]
b : tensor([[1, 2, 3],
        [4, 5, 6]])


In [60]:
np.add(a, 1, out=a)

print('a :', a)
print('b :', b)

a : [[2 3 4]
 [5 6 7]]
b : tensor([[2, 3, 4],
        [5, 6, 7]])


In [56]:
#torch to numpy
print('x :', x)

xx = x.numpy()
print('xx :', xx)

x : tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
xx : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [57]:
#x.numpy just copy the data of x

x.add_(1)
print('x :', x)
print('xx :', xx)

x : tensor([[ 2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21]])
xx : [[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]]
