In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad= True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
# y is created as a result of an operation, so it has grad_fn
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [7]:
a.requires_grad_(True)
print(a.requires_grad)

True


In [8]:
b = (a * a).sum()
print(b.grad_fn)

### Gradients
Let's backprop!

In [9]:
#before backprop x's grad is None

print(x.grad)

None


In [10]:
out.backward()

#out.backward is  equivalent to out.backward(torch.tensor(1.)) because out is a single scalar

In [11]:
print(x.grad)

#d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


For Jacobian-vector

In [14]:
x = torch.rand(3,  requires_grad = True)

y = x * 2

while y.data.norm() < 1000 :
    y = y  * 2

print(y)

tensor([ 514.1295,  257.8760, 1007.2756], grad_fn=<MulBackward0>)


In [15]:
#Now in this case y is no longer a scalar. torch.autograd could not compute the full Jacobian directly, 
#but if we just want the Jacobian-vector product, simply pass the vector to backward as argument:

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)

y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
